version: '3'

services:

  docker_mysql:
    image: mysql:latest
    container_name: cinema_db_mysql
    volumes:
      - ./mysql_data:/mysql_data
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dbAdmin
      - MYSQL_DATABASE=cinema_db
      - MYSQL_PASSWORD=password
